### ISSUE TITLE
Revisar "Analisis de los metodos para paisajes" y "Analisis de los metodos para rostros"

### ISSUE THREAD

**Issue by FrancoNegri** [ricardogcolombo/metodos2015#10]
El método de spines calculaba mal y las imagenes rompían. Al arreglarlo, volví a correr las imágenes y ahora el texto no es coherente con los resultados obtenidos.

**Comment by gzanitti** [comment]
Me parecia. A eso me referia con lo de 'estoy pisando sobre seguro'. 
A la tarde reescribo las cosas incoherentes.
