### ISSUE TITLE
p4. Complejidad

### ISSUE THREAD

**Issue by impronunciable** [ricardogcolombo/metodos2015#2]
En la complejidad usan el "n" para la altura y el ancho... Y si no es cuadrada? Asumieron esto?

Notación Q11, Q12,... a que pixel se refieren con cada uno? (podrían agregar un ejemplo para esto)

Hablan de usar un polinomio interpolador: quedaría siempre una recta.

Lo calculan para cada uno haciendo todas las cuentas? Podrían completar usando que son rectas.

**Comment by ricardogcolombo** [comment]
Commit que cierra el issue 80977c20e4f90f40922f9f8e92a13c8ff0c123e0
